name: check_labels

on:
  push:
    branches-ignore:
      - main

jobs:
  perform_check:
    if: github.event.pusher.name != 'ms3_package-bot'
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: main
          token: ${{ secrets.MS3_BOT_TOKEN }}
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: modified
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display changed files
        run: |
          echo "${{ steps.modified.outputs.modified }}"
          echo "${{ join(steps.modified.outputs.modified) }}"
          cat ${HOME}/files_modified.json
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Clone ms3_package
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3_package
          ref: workflow
          path: ./ms3_package
      - name: Install ms3_package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ms3
      - name: Run ms3_package check
        working-directory: ./main
        run: |
          ms3 check -f ${HOME}/files_modified.json --assertion
